[package]
name = "myinsurfi_contracts"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.6.3"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "audited"

[tool.snforge]
exit_first = true

[scripts]
test = "snforge test"
build = "scarb build"
format = "scarb fmt"